language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - "npm install --global gatsby"
script:
  - "npm run deploy"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $ghtoken
  on:
    branch: master